name: Build Ubuntu 18.04

on:
  pull_request:
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "/docs/**"
      - "/samples/**"
      - "**.md"

jobs:
  build:
    uses: EventStore/EventStore/.github/workflows/build-reusable.yml@multi-workflow
    with:
      os: ubuntu-18.04
