name: Build Ubuntu 18.04

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

jobs:
  build:
    uses: EventStore/EventStore/.github/workflows/build-reusable.yml@d274d7d528800d72cfac3d496dc747fba5208ff3
    with:
      os: ubuntu-18.04
      arch: x64
