name: Build Ubuntu 18.04

on:
  pull_request:
    paths-ignore:
      - "/docs/**"
      - "/samples/**"
      - "**.md"
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "/docs/**"
      - "/samples/**"
      - "**.md"

jobs:
  build:
    uses: EventStore/EventStore/.github/workflows/build-reusable.yml@9aceaed29d75e9fd70742aae0574dbc9e1d4f472
    with:
      os: ubuntu-18.04
      arch: x64
