name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "/docs/**"
      - "/samples/**"
      - "**.md"

jobs:
  build-container:
    uses: EventStore/EventStore/.github/workflows/build-container-reusable.yml@multi-workflow
  build:
    uses: EventStore/EventStore/.github/workflows/build-reusable.yml@multi-workflow
