name: Tag Docker Images
on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3am UTC.
  workflow_dispatch:
jobs:
  tag-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and Push
        uses: EventStore/Automations/tag-docker-images@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}